### ISSUE TITLE
Output to YAML

### ISSUE THREAD

**Issue by samrocketman** [hmarr/codeowners#41]
It would be cool if this outputs to YAML.  Do you accept pull requests?

Here's a fast proof of concept I use with `awk`.

### Example output

The following example assumes I have `~/usr/bin` in my `$PATH`.

```bash
$ curl -sSfL https://github.com/hmarr/codeowners/releases/download/v1.2.1/codeowners_1.2.1_darwin_arm64.tar.gz | tar -xz -C ~/usr/bin/ codeowners

$ cat > ~/usr/bin/codeowners-to-yaml.awk <<'EOF'
#!/usr/bin/awk -f
BEGIN {
    print "codeowners:";
};
{
    print "  - file: \""$1"\"\n    reviewers:";
    for(i=2; i<=NF; i++) {
        print "      - \""$i"\"";
    }
}
EOF

$ chmod 755 ~/usr/bin/codeowners-to-yaml.awk

$ git diff --diff-filter=AM --name-only "$(git merge-base origin/main HEAD)" HEAD | xargs codeowners | codeowners-to-yaml.awk
codeowners:
  - file: "some-file"
    reviewers:
      - "@org/team1"
      - "@org/team2"
  - file: "another-file"
    reviewers:
      - "@org/team3"
```

The YAML produced by the above PoC from `codeowners` output.

```yaml
codeowners:
  - file: "some-file"
    reviewers:
      - "@org/team1"
      - "@org/team2"
  - file: "another-file"
    reviewers:
      - "@org/team3"
```

**Comment by samrocketman** [comment]
# New script for output to YAML

See [`codeowners.sh` in my dotfiles repository](https://github.com/samrocketman/home/blob/e03fff3c2bb981239ab85317c280ff7ccc5e48d9/bin/codeowners.sh).

# About script

I desire to see a list of individuals or teams which can provide overall approval for a pull request.

![Image](https://github.com/user-attachments/assets/f6133417-d42e-4a90-a2e7-69e37a39fc05)

As part of this, I decided to publish a shell script for my purposes.

### Details about the script

- Translates `(unowned)` to `(anyone_with_write_access)` so that it's more clear.
- Converts `codeowner` output to TSV.  Files with space in name is supported unlike my original example in description.
- Coverts "codeowner TSV" to `codeowners.yaml`.
- Analyzes `codeowners.yaml` in order to determine overall approvers according to CODEOWNERS.  Sometimes two groups can own two file trees and knowing this up front might help me to determine I should file two pull requests when contributing to open source projects.
- Prints out overall approvers.

### Sample output

Some files not owned with some files owned.

```yaml
overall_approvers:
  - @samrocketman
codeowners_by_file:
  - file: "bin/java_class_compatibility.sh"
    reviewers:
      - "(anyone_with_write_access)"
  - file: "misc/download-utilities.yml"
    reviewers:
      - "@samrocketman"
```

When files are owned by two teams and no one group or person can approve the whole PR.

```yaml
# overall_approvers: There are no overall approvers from CODEOWNERS.
codeowners_by_file:
  - file: "bin/java_class_compatibility.sh"
    reviewers:
      - "@org/another-team"
  - file: "misc/download-utilities.yml"
    reviewers:
      - "@samrocketman"
```

`CODEOWNERS` file exists but changed files aren't owned by anybody in particular.

```yaml
# overall_approvers: There are no overall approvers from CODEOWNERS.
codeowners_by_file:
  - file: "bin/java_class_compatibility.sh"
    reviewers:
      - "(anyone_with_write_access)"
  - file: "misc/download-utilities.yml"
    reviewers:
      - "(anyone_with_write_access)"
```

`CODEOWNERS` doesn't exist in the project and shell script will surface `codeowners` CLI errors.

```bash
$ codeowners.sh 
could not find CODEOWNERS file at any of the standard locations

$ echo $?
123
```

**Comment by samrocketman** [comment]
https://github.com/samrocketman/home/blob/main/bin/codeowners.sh

See latest main branch for updated code.  I'm going to stop updating this issue after this.  As a feature request this support built-in would be nice but I get what I want out of this utility combined with my wrapper shell script.

Mixed ownership.

```
$ codeowners.sh -- README.md another_file
```

```yaml
overall_approvers:
  - @samrocketman
codeowners_by_file:
  - file: "README.md"
    reviewers:
      - "@samrocketman"
  - file: "another_file"
    reviewers:
      - "(anyone_with_write_access)"
```

Skip unowned files.

```
$ codeowners.sh --skip-unowned-files -- README.md another_file
```

```yaml
overall_approvers:
  - @samrocketman
codeowners_by_file:
  - file: "README.md"
    reviewers:
      - "@samrocketman"
```

Lack of ownership (anyone with write access can approve).

```
$ codeowners.sh --skip-unowned-files -- another_file
```

```yaml
# overall_approvers: There are no overall approvers from CODEOWNERS.
codeowners_by_file: [] # no files require specific review from CODEOWNERS.
```
